spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tower_register?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Gdjk@2020

logging:
  level:
    org.springframework.web: debug